#!/bin/bash
# Discard settings button
sed -i "s/className=\"flex-1 py-2 px-3 flex items-center justify-center gap-1.5 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100 rounded-lg text-xs font-semibold transition-colors cursor-pointer disabled:opacity-50 border border-black\/5 dark:border-zinc-700\/60\"/className=\"flex-1 py-2 px-3 flex items-center justify-center gap-1.5 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100 rounded-lg text-xs font-semibold transition-colors cursor-pointer disabled:opacity-50 border border-black\/5 dark:border-zinc-700\/60 shadow-2xs\"/g" src/components/Sidebar.tsx

# Load sample JSON button (if present)
sed -i "s/className=\"flex-1 py-2 flex items-center justify-center bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 transition-colors cursor-pointer\"/className=\"flex-1 py-2 flex items-center justify-center bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg border border-black\/5 dark:border-zinc-700\/60 shadow-2xs text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 transition-colors cursor-pointer\"/g" src/components/Sidebar.tsx

# Generic bottom buttons (like print preview, download pdf)
sed -i "s/className=\"flex-1 py-2 flex items-center justify-center bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 transition-colors cursor-pointer disabled:opacity-50\"/className=\"flex-1 py-2 flex items-center justify-center bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg border border-black\/5 dark:border-zinc-700\/60 shadow-2xs text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 transition-colors cursor-pointer disabled:opacity-50\"/g" src/components/Sidebar.tsx

# Collapsed sidebar icons
sed -i "s/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 active:bg-zinc-300 rounded-lg text-zinc-600 hover:text-zinc-900 transition-colors cursor-pointer\"/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 active:bg-zinc-300 rounded-lg border border-black\/5 shadow-2xs text-zinc-600 hover:text-zinc-900 transition-colors cursor-pointer\"/g" src/components/Sidebar.tsx

sed -i "s/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg text-zinc-600 dark:text-zinc-300 transition-colors cursor-pointer\"/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 rounded-lg border border-black\/5 dark:border-zinc-700\/60 shadow-2xs text-zinc-600 dark:text-zinc-300 transition-colors cursor-pointer\"/g" src/components/Sidebar.tsx

sed -i "s/className=\"p-2 text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100 dark:text-zinc-400 dark:hover:text-zinc-200 dark:hover:bg-zinc-800 rounded-lg transition-colors cursor-pointer\"/className=\"p-2 text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100 dark:text-zinc-400 dark:hover:text-zinc-200 dark:hover:bg-zinc-800 rounded-lg border border-transparent hover:border-black\/5 dark:hover:border-zinc-700\/60 hover:shadow-2xs transition-all cursor-pointer\"/g" src/components/Sidebar.tsx

sed -i "s/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 rounded-lg transition-colors cursor-pointer\"/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 rounded-lg border border-black\/5 dark:border-zinc-700\/60 shadow-2xs transition-colors cursor-pointer\"/g" src/components/Sidebar.tsx

sed -i "s/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 rounded-lg transition-colors cursor-pointer disabled:opacity-50\"/className=\"p-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100 rounded-lg border border-black\/5 dark:border-zinc-700\/60 shadow-2xs transition-colors cursor-pointer disabled:opacity-50\"/g" src/components/Sidebar.tsx

